#!/run/current-system/sw/bin/bash
# (that shebang is nixos-specific)

# ln -s ../../post-commit .git/hooks/post-commit

if [[ ! -e .git/rebase-merge/done ]]; then

nix run "git+file:.?ref=HEAD#generate-docs" > docs.md
git diff --quiet docs.md
if [ $? -ne 0 ]; then

git add docs.md
git commit --no-verify --amend --no-edit
nix run --no-warn-dirty .#generate-docs > docs.md

fi

fi
