#!/run/current-system/sw/bin/bash
# (that shebang is nixos-specific)

if [[ ! -e .git/rebase-merge/done ]]; then

# buffer the output of nix eval through a temporary file
# because that way, we can move it to the new place atomically
# vs clearing the file during eval.

# in other words, this is reimplementing sponge(1)
# why not just use sponge? because this runs in CI (which doesn't have sponge)
tmp="$(mktemp)"

nix eval --raw "git+file:.?ref=HEAD#__docs" > $tmp

# GitHub Actions doesn't seem to have a HEAD ref (???)
if [ $? -ne 0 ]; then
echo "git didn't like the HEAD i gave it; falling back to working directory" >&2
nix eval --raw .#__docs $tmp
fi

mv $tmp docs.md

git diff --quiet docs.md
if [ $? -ne 0 ]; then

git add docs.md
git commit --no-verify --amend --no-edit

# restore the docs from the working directory if you commit with unstaged changes
nix eval --no-warn-dirty --raw .#__docs > $tmp

mv $tmp docs.md

fi

rm $tmp

fi
